server:
  port: 7777

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://118.178.87.26:3306/Architecture?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Qq977033704@
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.seven.springboot.pojo
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    default-statement-timeout: 10000
